### ISSUE TITLE
Service ICorrelationInfoAccessor<MessageCorrelationInfo> is null

### ISSUE THREAD

**Issue by meersschautarnaud** [arcus-azure/arcus.messaging#98] opened 2020-06-30 08:20 UTC
**Describe the bug**
Getting the service for [ICorrelationInfoAccessor<MessageCorrelationInfo>](https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs#L447) returns null.

**To Reproduce**
Create a class that derives from CloudEventBackgroundJob and add it as a hosted service.

```c#
services.AddHostedService(serviceProvider =>
{
	var apiConfiguration = serviceProvider.GetRequiredService<IApiConfiguration>();

	var settings = new AzureServiceBusMessagePumpSettings(
		entityName: "itmse-enroll-keyvaultevents-topic",
		subscriptionName: $"Prefix-{Guid.NewGuid()}",
		serviceBusEntity: ServiceBusEntity.Topic,
		getConnectionStringFromConfigurationFunc: config => config["ServiceBusTopicConnectionString"].ToString(),
		getConnectionStringFromSecretFunc: null,
		options: new AzureServiceBusMessagePumpConfiguration(AzureServiceBusTopicMessagePumpOptions.Default),
		serviceProvider: serviceProvider);

	var configuration = serviceProvider.GetRequiredService<IConfiguration>();
	var logger = serviceProvider.GetRequiredService<ILogger<AzureServiceBusMessagePump>>();
	var secretProvider = serviceProvider.GetRequiredService<IKeyVaultSecretProvider>();
	var cachedProvider = serviceProvider.GetRequiredService<ICachedSecretProvider>();

	return new KeyVaultEventsBackgroundService(settings, secretProvider, cachedProvider, apiConfiguration, configuration, serviceProvider, logger);
});
```

**Expected behavior**
The eventhub message get processed.

**Additional context**
 - .NET version 3.1

**Comment by stijnmoreels** [comment] 2020-06-30 08:24
Hi! Thanks for this.
The reason it returns `null` is because the correlation is not configured correctly.
As you can see [here](https://github.com/arcus-azure/arcus.messaging/blob/616fca6865a6095e44cd3fe5e11d12f04145a76e/src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs#L646), we call the `.AddCorrelation` on the services when registering the Azure Service Bus Message Pump. If it gets registered another way (like yours) you have to call this yourself.

**Comment by meersschautarnaud** [comment] 2020-06-30 08:44
I registered the service the way it is done [here](https://github.com/arcus-azure/arcus.backgroundjobs/blob/master/src/Arcus.BackgroundJobs.CloudEvents/Extensions/IServiceCollectionExtensions.cs#L21) because we're not using the Arcus secret provider. Using the `.AddCorrelation` in the startup, doesn't resolve the issue.

**Comment by stijnmoreels** [comment] 2020-06-30 09:23
What version messaging and background jobs are you using? Bc it seems to me that we haven't yet released this functionality yet?

**Comment by stijnmoreels** [comment] 2020-06-30 09:59
🤔 Then that version doesn't even has correlation as in 'correlation accessors'. Can you give some info on the startup/program/... where it fails exactly? Bc it seems that it is using our files directly maybe?

**Comment by meersschautarnaud** [comment] 2020-06-30 10:08
The application threw an exception (`Exception thrown: 'System.InvalidOperationException' in Arcus.Messaging.Pumps.Abstractions.dll`) when an event came in. To debug this behavior, I'm using the files on master indeed. So this would mean that the exception is due to something else and not an issue with correlation?

**Comment by stijnmoreels** [comment] 2020-07-01 05:21
Yes, proparly nothing to do with correlation. [Here's](https://github.com/arcus-azure/arcus.messaging/blob/v0.1.0/src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs) the message pump on that version.
What's the exception message? Invalid operation typically means that the setup or interaction with the different components here is called in a manner that is unexpected. An object that is in an invalid state to be functioning correctly. Hence, invalid operation.

It could mean that there's no message handler configered, ot none that can accept the received message, or...
So what's the message of this exception you have?
If you want to debug it yourself, try using the version on this repo with the tag `v0.1.0`: https://github.com/arcus-azure/arcus.messaging/tree/v0.1.0.

**Comment by tomkerkhove** [comment] 2020-07-01 05:27
@stijnmoreels Can you see if you can reproduce it by using @meersschautarnaud his steps above?

**Comment by stijnmoreels** [comment] 2020-07-01 05:31
> @stijnmoreels Can you see if you can reproduce it by using @meersschautarnaud his steps above?

I don't think I have enough info on how this is set up to make a reasonable reproduction of the problem.

**Comment by tomkerkhove** [comment] 2020-07-01 05:48
The above looks pretty clear, no?

Derive from CloudEventBackgroundJob and wire it up like they are doing, no?

**Comment by stijnmoreels** [comment] 2020-07-01 06:23
I can start this without problems, I can't find enough info to actually run the pump but it seems that it is the same as [this one](https://github.com/arcus-azure/arcus.backgroundjobs/blob/v0.1.0/src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs) where we have running integration tests against.

**Comment by tomkerkhove** [comment] 2020-07-01 06:45
Doing what's on https://github.com/arcus-azure/arcus.backgroundjobs/blob/v0.1.0/src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs is not exactly the same as is being done here: https://github.com/arcus-azure/arcus.messaging/issues/98#issue-647970686 where the hosted service is created manually.

**Comment by meersschautarnaud** [comment] 2020-07-09 12:03
I had a look at the code from v0.1.0 and identified the issue. Right [here](https://github.com/arcus-azure/arcus.messaging/blob/v0.1.0/src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs#L105) the `.SubstractFrom()` method returns an empty list. I suppose I have to add some DI next to the hosted service?

**Comment by stijnmoreels** [comment] 2020-07-15 05:21
Yes, the `.WithServiceBusMessageHamdler` and `.WithMessageHandler` on the `IServiceCollection` help with this.

**Comment by stijnmoreels** [comment] 2020-07-28 06:51
@meersschautarnaud , what is the status of this problem, have you find the necessary info/docs?

**Comment by tomkerkhove** [comment] 2021-06-16 11:23
Any update on this @meersschautarnaud ?

**Comment by meersschautarnaud** [comment] 2021-06-16 19:33
At the time, we were not able to get the background service of Arcus to work and wrote our own background service to handle the Azure KeyVault events. I'll create an application to test this again and let you know if I experience any issues.

**Comment by tomkerkhove** [comment] 2021-06-17 05:37
Thanks!

**Comment by stijnmoreels** [comment] 2022-01-13 10:03
@meersschautarnaud , is this still an issue? Otherwise we can close this.

**Comment by meersschautarnaud** [comment] 2022-01-23 15:08
@stijnmoreels this issue can be closed 👍

**Closed** 2022-01-23 15:09 UTC
Labels: area:correlation
